pipeline {
	agent any
	environment {
        dockerImageName = "docker.slc.crengland.com/cre/myservice"
		
    }
	stages{
		stage('Clone repository') {
			steps{
                checkout scm
			}
		}
        stage('DEV'){
			when{
				branch 'feature/*'
			}
			environment { 
                image = "${dockerImageName}:1.0.${env.BUILD_NUMBER}-dev" 
            }
			steps{
				bat "echo Build For DEV ${dockerImageName}"
				bat "echo Build in DEV"
			}
		}
		stage('QA'){
			when{
				branch 'QA-SNAPSHOT'
			}
			environment { 
                image = "${dockerImageName}:1.0.${env.BUILD_NUMBER}-qa" 
            }
			steps{
				bat "echo Build For QA ${env.BRANCH_NAME}"
				bat "echo Build in QA"
			}
		}
		stage('PROD'){
			when{
				branch 'master'
			}
			environment { 
                image = "${dockerImageName}:1.0.${env.BUILD_NUMBER}-prod" 
            }
			steps{
				script {
                    currentBuild.displayName = "1.0.${env.BUILD_NUMBER}-prod"
                    currentBuild.description = "${dockerImageName}:1.0.${env.BUILD_NUMBER}-prod" 
                }
				bat "echo Build For Prod ${image}"
				bat "echo Build in PROD"
			}
		}	
    }

}