pipeline {
	agent any
	stages{
		
		
		stage('Clone repository') {
			steps{
                checkout scm
			}
		}

		stage('PROD'){
			when{
				branch 'master'
			}
			steps{
				bat "echo Build For Prod ${env.BRANCH_NAME}"
				bat "echo Build in PROD"
			}

		}
		
        stage('DEV'){
			when{
				branch 'feature/*'
			}
			
					steps{
						bat "echo Build For DEV ${env.BRANCH_NAME}"
						bat "echo Build in DEV"
					}
		}
				
    }

}